node {
    // Define the Docker container and environment variable
    def dockerImage = 'node:lts-buster-slim'
    def dockerArgs = '-p 3000:3000'
    def ciEnvironment = [CI: 'true']

    // Use Docker container
    docker.image(dockerImage).inside(dockerArgs) {
        // Set environment variables
        withEnv(["CI=${ciEnvironment.CI}"]) {

            // Build Stage
            stage('Build') {
                sh 'npm install'
            }

            // Test Stage
            stage('Test') {
                sh './jenkins/scripts/test.sh'
            }

            // Deliver Stage
            stage('Deliver') {
                sh './jenkins/scripts/deliver.sh'
                
                // Pause for user input before proceeding
                input message: 'Finished using the website? (Click "Proceed" to continue)'
                
                // Clean up or kill processes
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
